name: PHP_pipeline

on:
  push:
    branches:
      - master

jobs:
  checkstyle_project:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone repo
        uses: actions/checkout@v2

      - name: Set version PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install dependencies php
        run: |
          sudo apt-get install -y php-pear
          sudo apt-get install -y php-dev
          sudo pecl install phpcs
          phpcs --config-set default_standard PSR12

      - name: Check style project
        continue-on-error: true
        run: |
          phpcs .